//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariocaMix.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CariocaMix.Utils.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve conter {1}..
        /// </summary>
        public static string A_X0_DEVE_CONTER_X1 {
            get {
                return ResourceManager.GetString("A_X0_DEVE_CONTER_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ser maior ou igual a {1}..
        /// </summary>
        public static string A_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1 {
            get {
                return ResourceManager.GetString("A_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ser menor ou igual a {1}..
        /// </summary>
        public static string A_X0_DEVE_SER_MENOR_OU_IGUAL_A_X1 {
            get {
                return ResourceManager.GetString("A_X0_DEVE_SER_MENOR_OU_IGUAL_A_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As {0} não podem ser iguais!.
        /// </summary>
        public static string AS_X0_NAO_PODEM_SER_IGUAIS {
            get {
                return ResourceManager.GetString("AS_X0_NAO_PODEM_SER_IGUAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As {0} não são iguais!.
        /// </summary>
        public static string AS_X0_NAO_SAO_IGUAIS {
            get {
                return ResourceManager.GetString("AS_X0_NAO_SAO_IGUAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados não encontrados..
        /// </summary>
        public static string DADOS_NAO_ENCONTRADOS {
            get {
                return ResourceManager.GetString("DADOS_NAO_ENCONTRADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao cadastrar {0}.
        /// </summary>
        public static string ERRO_AO_CADASTRAR_X0 {
            get {
                return ResourceManager.GetString("ERRO_AO_CADASTRAR_X0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao processar {0}! Verifique {1} e tente novamente!!.
        /// </summary>
        public static string ERRO_AO_PROCESSAR_X0_VERIFIQUE_X1_E_TENTE_NOVAMENTE {
            get {
                return ResourceManager.GetString("ERRO_AO_PROCESSAR_X0_VERIFIQUE_X1_E_TENTE_NOVAMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um {0} chamado {1}..
        /// </summary>
        public static string JA_EXISTE_UM_X0_CHAMADO_X1 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_CHAMADO_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um {0} com a {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UM_X0_COM_A_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_COM_A_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um {0} com o {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UM_X0_COM_O_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_COM_O_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma {0} chamada {1}..
        /// </summary>
        public static string JA_EXISTE_UMA_X0_CHAMADA_X1 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UMA_X0_CHAMADA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma {0} com a {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UMA_X0_COM_A_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UMA_X0_COM_A_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma {0} com o {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UMA_X0_COM_O_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UMA_X0_COM_O_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir um {0} associado a um {1}..
        /// </summary>
        public static string NAO_E_POSSIVEL_EXCLUIR_UM_X0_ASSOCIADO_A_UM_X1 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_UM_X0_ASSOCIADO_A_UM_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir um {0} associado a uma {1}..
        /// </summary>
        public static string NAO_E_POSSIVEL_EXCLUIR_UM_X0_ASSOCIADO_A_UMA_X1 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_UM_X0_ASSOCIADO_A_UMA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir uma {0} associada a um {1}..
        /// </summary>
        public static string NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UM_X1 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UM_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir uma {0} associada a uma {1}..
        /// </summary>
        public static string NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UMA_X1 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UMA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token expirou!.
        /// </summary>
        public static string O_TOKEN_EXPIROU {
            get {
                return ResourceManager.GetString("O_TOKEN_EXPIROU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} deve conter {1}..
        /// </summary>
        public static string O_X0_DEVE_CONTER_X1 {
            get {
                return ResourceManager.GetString("O_X0_DEVE_CONTER_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} deve ser maior ou igual a {1}..
        /// </summary>
        public static string O_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1 {
            get {
                return ResourceManager.GetString("O_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} deve ser menor ou igual a {1}..
        /// </summary>
        public static string O_X0_DEVE_SER_MENOR_OU_IGUAL_A_X1 {
            get {
                return ResourceManager.GetString("O_X0_DEVE_SER_MENOR_OU_IGUAL_A_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} não existe!.
        /// </summary>
        public static string O_X0_NAO_EXISTE {
            get {
                return ResourceManager.GetString("O_X0_NAO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto {0} é obrigatório..
        /// </summary>
        public static string OBJETO_X0_E_OBRIGATORIO {
            get {
                return ResourceManager.GetString("OBJETO_X0_E_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao adicionar {0}.
        /// </summary>
        public static string OCORREU_UM_ERRO_AO_ADICIONAR_X0 {
            get {
                return ResourceManager.GetString("OCORREU_UM_ERRO_AO_ADICIONAR_X0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao {0}.
        /// </summary>
        public static string OCORREU_UM_ERRO_AO_X0 {
            get {
                return ResourceManager.GetString("OCORREU_UM_ERRO_AO_X0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso..
        /// </summary>
        public static string OPERACAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("OPERACAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pergunta adicionada com sucesso!.
        /// </summary>
        public static string PERGUNTA_ADICIONADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("PERGUNTA_ADICIONADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perguntas frequentes.
        /// </summary>
        public static string PERGUNTAS_FREQUENTES {
            get {
                return ResourceManager.GetString("PERGUNTAS_FREQUENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tempo limite para troca da senha foi esgotado..
        /// </summary>
        public static string TEMPO_LIMITE {
            get {
                return ResourceManager.GetString("TEMPO_LIMITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já existe!.
        /// </summary>
        public static string USUARIO_JA_EXISTE {
            get {
                return ResourceManager.GetString("USUARIO_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não existe!.
        /// </summary>
        public static string USUARIO_NAO_EXISTE {
            get {
                return ResourceManager.GetString("USUARIO_NAO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adicionada com sucesso!.
        /// </summary>
        public static string X0_ADICIONADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ADICIONADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adicionado com sucesso!.
        /// </summary>
        public static string X0_ADICIONADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ADICIONADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alterada com sucesso!.
        /// </summary>
        public static string X0_ALTERADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alteradas com sucesso!.
        /// </summary>
        public static string X0_ALTERADAS_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADAS_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alterado com sucesso!.
        /// </summary>
        public static string X0_ALTERADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alterados com sucesso!.
        /// </summary>
        public static string X0_ALTERADOS_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADOS_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} autenticado com sucesso!.
        /// </summary>
        public static string X0_AUTENTICADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_AUTENTICADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cadastrada com sucesso!.
        /// </summary>
        public static string X0_CADASTRADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_CADASTRADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cadastrado com sucesso!.
        /// </summary>
        public static string X0_CADASTRADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_CADASTRADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ser preenchida!.
        /// </summary>
        public static string X0_DEVE_SER_PREENCHIDA {
            get {
                return ResourceManager.GetString("X0_DEVE_SER_PREENCHIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser preenchido!.
        /// </summary>
        public static string X0_DEVE_SER_PREENCHIDO {
            get {
                return ResourceManager.GetString("X0_DEVE_SER_PREENCHIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatória..
        /// </summary>
        public static string X0_E_OBRIGATORIA {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatória e deve conter {1} caracteres..
        /// </summary>
        public static string X0_E_OBRIGATORIA_E_DEVE_CONTER_X1_CARACTERES {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIA_E_DEVE_CONTER_X1_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório..
        /// </summary>
        public static string X0_E_OBRIGATORIO {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório e deve conter {1} caracteres..
        /// </summary>
        public static string X0_E_OBRIGATORIO_E_DEVE_CONTER_X1_CARACTERES {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO_E_DEVE_CONTER_X1_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enviado com sucesso!.
        /// </summary>
        public static string X0_ENVIADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ENVIADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} excluída com sucesso!.
        /// </summary>
        public static string X0_EXCLUIDA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_EXCLUIDA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} excluído com sucesso!.
        /// </summary>
        public static string X0_EXCLUIDO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_EXCLUIDO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválida!.
        /// </summary>
        public static string X0_INVALIDA {
            get {
                return ResourceManager.GetString("X0_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválida! {1}.
        /// </summary>
        public static string X0_INVALIDA_X1 {
            get {
                return ResourceManager.GetString("X0_INVALIDA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválidas!.
        /// </summary>
        public static string X0_INVALIDAS {
            get {
                return ResourceManager.GetString("X0_INVALIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválido!.
        /// </summary>
        public static string X0_INVALIDO {
            get {
                return ResourceManager.GetString("X0_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválido! {1}.
        /// </summary>
        public static string X0_INVALIDO_X1 {
            get {
                return ResourceManager.GetString("X0_INVALIDO_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválidos!.
        /// </summary>
        public static string X0_INVALIDOS {
            get {
                return ResourceManager.GetString("X0_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrada..
        /// </summary>
        public static string X0_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("X0_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrado..
        /// </summary>
        public static string X0_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("X0_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não enviado!.
        /// </summary>
        public static string X0_NAO_ENVIADO {
            get {
                return ResourceManager.GetString("X0_NAO_ENVIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não está ativo!.
        /// </summary>
        public static string X0_NAO_ESTA_ATIVO {
            get {
                return ResourceManager.GetString("X0_NAO_ESTA_ATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não informado..
        /// </summary>
        public static string X0_NAO_INFORMADO {
            get {
                return ResourceManager.GetString("X0_NAO_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não permitid{1}!.
        /// </summary>
        public static string X0_NAO_PERMITID_X1 {
            get {
                return ResourceManager.GetString("X0_NAO_PERMITID_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatória e deve conter entre {1} e {2} caracteres..
        /// </summary>
        public static string X0_OBRIGATORIA_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES {
            get {
                return ResourceManager.GetString("X0_OBRIGATORIA_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório e deve conter entre {1} e {2} caracteres..
        /// </summary>
        public static string X0_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES {
            get {
                return ResourceManager.GetString("X0_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ou {1} incorreto..
        /// </summary>
        public static string X0_OU_X1_INCORRETO {
            get {
                return ResourceManager.GetString("X0_OU_X1_INCORRETO", resourceCulture);
            }
        }
    }
}
